"""Column edited migration1.

Revision ID: ed4ef97d1780
Revises: e60272d71711
Create Date: 2023-08-16 00:28:09.921149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4ef97d1780'
down_revision = 'e60272d71711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('edited',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('edited',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
